---
- hosts: lab
  tasks:
    - name: Remove old ckan image
      shell: docker pull 192.168.1.200:5000/ckan:latest

    - name: Pull latest ckan image
      shell: docker pull 192.168.1.200:5000/ckan:latest

    - name: Stop ckan container
      shell: docker stop ckan

    - name: Remove ckan container
      shell: docker rm ckan

    - name: Start latest ckan container
      shell: docker run -d --name ckan -p 80:80 --link db:db --link solr:solr 192.168.1.200:5000/ckan:latest
